### ISSUE TITLE
Manage mount of storage devices

### ISSUE THREAD

**Issue by btravouillon** [mila-iqia/ansible-role-bareos#16]
## Description of the feature request

The configuration of a new storage device with File as storage backend should include the mount of the block devices.

## Current Issue

The directories must be owned by `bareos` which does not exist before the installation of Bareos. On a fresh install, if the mounts are configured **before** running this role, then the task will fail.

```
TASK [foo.mount : Ensure mountpoints exist] ***********************
 failed: [bareos] (item={'path': '/vol0007', 'owner': 'bareos', 'group': 'bareos', 'mode': '0770',
  'source': '/dev/mapper/vol0007'}) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", 
  "item": {"group": "bareos", "mode": "0770", "owner": "bareos", "path": "/vol0007",
  "source": "/dev/mapper/vol0007"}, "mode": "0755", "msg": "chown failed: failed to look up user bareos",
  "owner": "root", "path": "/vol0007", "size": 4096, "state": "directory", "uid": 0}
```

## Proposed implementation

Use the module [ansible.posix.mount](https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html) in a task that iterates over a new variable `bareos_mounts`.

```
bareos_mounts:
  - path: /vol0007
    owner: bareos
    group: bareos
    mode: '0770'
    source: /dev/mapper/vol0007
  - [...]
```

Another option could be to expand the `bareos_devices` parameter with the block device.

```
bareos_devices:
  - name: FileStoragevol0007
    arch_device: /vol0007
    block_device: /dev/mapper/vol0007
```

The task could then use the module [ansible.posix.mount](https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html). The values for `owner`, `group` and `mode` could be set in the task since these should not be changed by the user (or they could be optional with sane defaults).
